// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjhpacIYm4n2jP7dbl2UYDncUaIcLMc8g',
    appId: '1:539264482292:web:e1861ce1983712c33817a1',
    messagingSenderId: '539264482292',
    projectId: 'youcareer-cf165',
    authDomain: 'youcareer-cf165.firebaseapp.com',
    storageBucket: 'youcareer-cf165.appspot.com',
    measurementId: 'G-X0XF9NGC63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4tcMWkkd7z_OQ0lTqSQxkrQix6-pO-oE',
    appId: '1:539264482292:android:36171b0640ef13213817a1',
    messagingSenderId: '539264482292',
    projectId: 'youcareer-cf165',
    storageBucket: 'youcareer-cf165.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh1ARlOK99KR8e5he0IOUaAQPZ7lJdDIY',
    appId: '1:539264482292:ios:5fad4858f9bf02603817a1',
    messagingSenderId: '539264482292',
    projectId: 'youcareer-cf165',
    storageBucket: 'youcareer-cf165.appspot.com',
    iosBundleId: 'com.example.yourcareer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh1ARlOK99KR8e5he0IOUaAQPZ7lJdDIY',
    appId: '1:539264482292:ios:d7123b41679568393817a1',
    messagingSenderId: '539264482292',
    projectId: 'youcareer-cf165',
    storageBucket: 'youcareer-cf165.appspot.com',
    iosBundleId: 'com.example.yourcareer.RunnerTests',
  );
}
